### PR TITLE
[PM-3152] Add autofill support for cromite

### PR DESCRIPTION
**Pull request by Bahasnyldz**
## Type of change
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other

## Objective
Bitwarden autofill doesn't work in cromite
 Cromite is fork of bromite aims to privacy and security.

## Code changes

* **AutofillHelpers.cs:** Added `"org.cromite.cromite",`
* **AccessibilityHelpers.cs:** Added `new Browser("org.cromite.cromite", "url_bar"),`
* **autofillservice.xml** Added `<compatibility-package
      android:name="org.cromite.cromite"
      android:maxLongVersionCode="10000000000"/>`
## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by srappan** [comment]
Hiya has their been any movement to merge this?

Thanks in advance

**Comment by unoukujou** [comment]
@djsmith85 what does it mean:

Merging is blocked
Merging can be performed automatically with 1 approving review.

Are you able to approve it? If so, thanks! I'm going crazy without being able to use autofill.

**Comment by gammaray05** [comment]
Yes please, there's an entire community of privacy oriented users that waits to use Cromite just because bitwarden can't be used.

**Comment by uazo** [comment]
in any case, it does not seem to me that if these changes are the correct ones.
cromite (like bromite, that patch I made) natively supports android autofill, so I think it goes in the `TrustedBrowsers` list rather than `CompatBrowsers`.
Obviously it has to be checked.

**Comment by varaki** [comment]
> @djsmith85 what does it mean:
> 
> Merging is blocked Merging can be performed automatically with 1 approving review.
> 
> Are you able to approve it? If so, thanks! I'm going crazy without being able to use autofill.

Until it's finally fixes, you can resort to manually searching for your vault item using the magnifying glass on the top right corner of the page that shows the "There are no items in your vault for org.cromite.cromite" message, then tap on the correct item, then select Auto-fill. It's a bit cumbersome, but at least you can avoid copypasting.

**Comment by unoukujou** [comment]
> > @djsmith85 what does it mean:
> > Merging is blocked Merging can be performed automatically with 1 approving review.
> > Are you able to approve it? If so, thanks! I'm going crazy without being able to use autofill.
> 
> Until it's finally fixed, you can resort to manually searching your vault using the magnifying glass on the top right corner of the page that shows the "There are no items in your vault for org.cromite.cromite" message, then tap on the correct search result, then select Auto-fill. It's a bit cumbersome, but at least you can avoid copypasting.

Thanks, I'll try that way. But it's also a bigger problem to save new logins. Bitwarden doesn't offer to save the new logins and I have to enter everything manually.

**Comment by varaki** [comment]
Any updates?

**Comment by chris122380** [comment]
Doesn't work on Bitwarden 2023.9.1

**Comment by unoukujou** [comment]
> Doesn't work on Bitwarden 2023.9.1

Still no update since 4 months.

Also Mulch browser... Same thing.

https://github.com/bitwarden/mobile/pull/2640
https://github.com/bitwarden/mobile/issues/2709
https://github.com/bitwarden/mobile/issues/2639
https://github.com/bitwarden/mobile/pull/2427

**Comment by chris122380** [comment]
> > Doesn't work on Bitwarden 2023.9.1
> 
> Still no update since 4 months.
> 
> Also Mulch browser... Same thing.
> 
> #2640 #2709 #2639 #2427

I have no issues running Bitwarden with Mulch browser. Are you using the app or the extension? I am using the app with no problems.

**Comment by Para-lyzed** [comment]
Since the Checkmarx check is failing, it may be necessary to recheck this PR before it is reviewed. After the Checkmarx check is successful, can you request a review @Bahasnyldz ?

**Comment by varaki** [comment]
> Hey everyone, currently no action is needed by @Bahasnyldz. This is in review by product management.

Cool, I just really hope it won't take another few months 🙂

**Review by fedemkr — APPROVED** [review]

**Comment by solomonrajan** [comment]
Any update regarding autofill, still not working in browser.

**Comment by fedemkr** [comment]
Hi everyone, this is currently being looked at by the QA team.

**Comment by 0xvino** [comment]
Hi there. Today is November 10th and this error has not yet been fixed in the Cromite browser

**Comment by fabian-st** [comment]
A fix would be much appreciated. Thanks for all your efforts.

**Comment by avipars** [comment]
https://community.bitwarden.com/t/allow-users-to-add-new-browser-to-the-autofill-whitelist/59706

**Comment by rootinchase** [comment]
What is the hold up on this issue? It's been in the hands of QA for over a month now.

Further more, what causes these issues to take so long to be remedied? This is not the first time that Bitwarden has taken an extremely long time to support a browser.

**Comment by dbosompem** [comment]
Hi All, apologies for taking long to merge this in. I admit that there has been a delay with QA, and so we're discussing this internally to merge this. Appreciate your patience!

**Comment by unoukujou** [comment]
> Hi All, apologies for taking long to merge this in. I admit that there has been a delay with QA, and so we're discussing this internally to merge this. Appreciate your patience!

Don't forget Mulch too.

https://github.com/bitwarden/mobile/pull/2427

**Comment by 1RandomDev** [comment]
By now I just cloned the repo and built my own version of the app with the changes applied. It's ridiculous how long it takes a company as big as Bitwarden to merge 3 lines of code adding support for a browser.

**Comment by unoukujou** [comment]
> By now I just cloned the repo and built my own version of the app with the changes applied. It's ridiculous how long it takes a company as big as Bitwarden to merge 3 lines of code adding support for a browser.

Plus the fact that this is also making bitwarden users less secure when we have to use copy and paste. It should be more priority especially when it's something so simple. Anyway, they're having a meeting to discuss it so that's good I guess? The sad part is that mainstream browsers that don't respect user privacy like Chrome will not have problems like this. Oh well...

**Comment by larena1** [comment]
> By now I just cloned the repo and built my own version of the app with the changes applied. It's ridiculous how long it takes a company as big as Bitwarden to merge 3 lines of code adding support for a browser.

It's always been like this. They don't react in issues, they promise to look into stuff but in reality they don't, it's just sad.

Horrible and inexperienced management. It's not even clear to me what all the people are constantly working on when there's so little to see in the end.

**Comment by varaki** [comment]
> > Hey everyone, currently no action is needed by @Bahasnyldz. This is in review by product management.
> 
> Cool, I just really hope it won't take another few months 🙂

Aaand it did... And still nothing, just "reviews" and "discussions" repeatedly over a few lines of code.
Not good.

**Comment by differsthecat** [comment]
Hi everyone, thank you again for your patience on this. I wanted to give a quick update that we expect QA to complete their testing next week and we will update with any findings or merge if it is good to go!

**Comment by larena1** [comment]
> Almost a year now. 😞

Please give QA some time. There has been a regularly long delay but they'll probably pick it up not very soon.

**Comment by fedemkr** [comment]
Hi everyone, QA has approved this so we move forward on merging this 🎉 . Thank you all for your patience and the contribution!

**Comment by larena1** [comment]
> It's still the same for me, checks for org.cromite.cromite instead of the actual URL.
> 
> *using the 2023.12.0 version

It will be in the next version in 1 or 2 months maybe. Please give it some more time. It hasn't even been 5 months yet.

**Comment by larena1** [comment]
> > > It's still the same for me, checks for org.cromite.cromite instead of the actual URL.
> > > *using the 2023.12.0 version
> > 
> > 
> > It will be in the next version in 1 or 2 months maybe. Please give it some more time. It hasn't even been 5 months yet.
> 
> ohh okay.. but just wondering: why not now? I mean it's merged already.

Because at Bitwarden things are done very thoroughly and therefore take a long time.

https://github.com/bitwarden/mobile/commits/v2023.12.0

Version 2023.12.0 does not include the Cromite commit.

**Comment by unoukujou** [comment]
In the meantime though, users are less secure using copy&paste. Android keeps warning me about apps accessing my clipboard. Something so simple and straightforward as this should really be updated quickly. Especially since having it makes users more secure and gives a much better/easier user experience.

**Comment by AlaisterLeung** [comment]
Version 2023.12.1 includes the Cromite commit.
We can download the build from GitHub Actions:
https://github.com/bitwarden/mobile/actions/runs/7118767114

**Comment by netizeni** [comment]
@AlaisterLeung is it possible to download .apk file from there somewhere? I was looking, but couldn't find it.

**Comment by AlaisterLeung** [comment]
> @AlaisterLeung is it possible to download .apk file from there somewhere? I was looking, but couldn't find it.

@netizeni  On that page, scroll down to Artifacts and download `com.x8bit.bitwarden.apk`

**Comment by larena1** [comment]
@uazo this doesn't really work as expected. When logging in to Google, it'll allow to autofill the username on the first screen but not the password on the next screen - Bitwarden won't even show above the keyboard when on the password screen. In Chrome, Bitwarden does work on both screens. 

Could this be due to you having implemented native autofill in Cromite and not just accessibility?

**Comment by netizeni** [comment]
> @netizeni On that page, scroll down to Artifacts and download `com.x8bit.bitwarden.apk`

Thank you! I just now notices you have to be logged in to download, I tried without login and then logged in to ask, lol.

**Comment by uazo** [comment]
> Could this be due to you having implemented native autofill in Cromite and not just accessibility?

theoretically, native autofill support does not replace compatibility mode, so I don't think it's because of that.
perhaps it is related to the "Fill passwords on account selection" chrome://flags/#fill-on-account-select flag being active by default, which forces the user to click on the element to initiate autofill

**Comment by Parsnip** [comment]
> > Could this be due to you having implemented native autofill in Cromite and not just accessibility?
> 
> theoretically, native autofill support does not replace compatibility mode, so I don't think it's because of that. perhaps it is related to the "Fill passwords on account selection" chrome://flags/#fill-on-account-select flag being active by default, which forces the user to click on the element to initiate autofill

As far as I can see toggling that flag has  no effect. For what it's worth as far as I can remember this might have been similarly broken in bromite as well.

**Comment by larena1** [comment]
@uazo do you think you can fix that maybe? It appears to happen on sites where there is just a password field like with two step login procedures where you enter the username first and then the password in the next step.

**Comment by uazo** [comment]
well, I don't know, if it's a bug then I introduced it, so I guess so.
but I need the context in a new issue in my repo, please.

**Comment by Fxzzi** [comment]
Cromite fill is available in 2024.1.0 🎉🎉

**Comment by adriy-be** [comment]
> > Hi everyone, thank you again for your patience on this. I wanted to give a quick update that we expect QA to complete their testing next week and we will update with any findings or merge if it is good to go!
> 
> I really hope - You guys can find a way to add browser support quicker in the future!

Totally agree !

**Pull request merged**
