### PR TITLE
[PS-2342] Implement argon2 configuration options

### PR DESCRIPTION
**Pull request by quexten**
## Type of change
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

This PR adds configuration option support for the argon2 kdf.

## Code changes
For all files: Basically anywhere where kdfIterations / kdfType is used (in requests, stateservice) we simply add the optional variables kdfMemory and kdfParalleism. The defaults are: 16 (MiB) for memory and 2 parallelism.

This is re-based to the latest argon2ios branch. I'll re-target this PR to master once https://github.com/bitwarden/mobile/pull/2309 is merged.

### CODE REVIEW

**Comment by quexten** [comment]
@kspearrin Shouldn't this PR still be open? The merged branch we merged has the static configuration for memory / parallelism. This one adds the dynamic memory / parallelism configuration.

**Comment by kspearrin** [comment]
Looks like it was automatically closed when I merged the other branch. We can reopen it and target master now.

**Comment by kspearrin** [comment]
@quexten Can you change the target branch to master? It won't allow me to re-open it since the target branch has been deleted.
image

**Comment by quexten** [comment]
@kspearrin Re-opened here https://github.com/bitwarden/mobile/pull/2328. I took the commit, and applied it on the latest master. There was a git error, which I can't check atm. Will check in ~2 hours, so be advised that 2 files might not compile.

**Pull request closed without merging**
