### PR TITLE
Updates images for the UWP login page

### PR DESCRIPTION
**Pull request by alistair23**
Update the login and cancel images for the UWP login page.

### CODE REVIEW

**Comment by kspearrin** [comment]
I am a bit confused by this PR. Why was this needed? This seems to break the existing iOS layout... ?

**Comment by alistair23** [comment]
On UWP apps the text isn't shown on the title bar unless you expand it. That means you only see the pictures. Without anything set it isn't clear there are buttons.

I didn't realise it'd break iOS. Is setting the image or is changing the cancel button layout the commit that breaks it?

**Comment by alistair23** [comment]
This is what it looks like before this PR
nologo-collapsed
and this is after this PR
logo-collapsed

**Comment by alistair23** [comment]
and this is after clicking the ...
logo-expanded

**Comment by kumarharsh** [comment]
Is there a timeline wrt when it'll be released to the store?

**Comment by alistair23** [comment]
I just updated the pull request for all the buttons that I could see.

This greatly improves the toolbar with UWP. I didn't test the other OSes though (I don't have a nice way to). If this breaks others we can add Windows if statements around them.

**Comment by kspearrin** [comment]
Unfortunately this adds buttons everywhere for the other OSes as well, which we do not want. The best way to handle this would be to create a custom Toolbar control that applies the if condition to add or remove the icons based on OS.

**Comment by alistair23** [comment]
Yep, I had an idea for this.

I think I'll add something to AppResources with device specific strings. So there can be AppResources.LogInImage which is NULL for all platforms besides UWP where it's a string.

I'll close this PR and open up a new one when I implement it.

**Comment by kspearrin** [comment]
AppResources is handled in the common `App` project, so that will not work. Just create a subclassed ToolbarItem in which you can handle the logic of show/hide image basic on OS.

**Comment by alistair23** [comment]
Ok, I'll do that then.

**Comment by alistair23** [comment]
Actually, does it make more sense to have helper functions like Helpers.GetEmptyTableSectionTitle() that handles the image types?

That way there can be one Helpers.LoginImage() function which can be called for all of them.

**Pull request closed without merging**
