### PR TITLE
[PM-3556] Change anonaddy to addy io

### PR DESCRIPTION
**Pull request by willbrowningme**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other
```

## Objective

To use the new API URL for addy.io and update the name after the rebrand - [https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/](https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/).

## Code changes

- Updated API URL to `https://app.addy.io/api/v1/aliases`.
- Updated translations and references to from `AnonAddy` to `AddyIo`.

The only translation value I haven't updated is the Hindi one as I'm not sure how you translated it - https://github.com/bitwarden/mobile/blob/master/src/App/Resources/AppResources.hi.resx#L2418

I have not built and tested these changes myself.

### CODE REVIEW

**Review by aj-rosado — CHANGES_REQUESTED** [review]
Thank you for your contribution @willbrowningme ! Really appreciate your time and effort on this.

I would like to ask you to revert the refactor changes if possible. The refactor is affecting the cached data so when the app is updated the cached ApiToken and domain are lost.

We would really like to have this on next release so to keep it simple we want to only change the texts and url for now.

If you don't have the opportunity to do it, I can change it myself 😃 

Thank you once again!

**Comment by willbrowningme** [comment]
@aj-rosado Thank you, I'm not sure exactly which bits to revert and which to leave so it might be best if you make the changes if possible please.

Thanks very much!

**Review by djsmith85 — APPROVED** [review]
Changes look good to me, but with my limited knowledge for mobile, requesting a review from @bitwarden/dept-development-mobile

**Review by fedemkr — APPROVED** [review]

**Review by aj-rosado — APPROVED** [review]
@willbrowningme I've made the necessary changes and I'm moving this to QA

**Comment by aj-rosado** [comment]
This was approved by QA and will be included on the next mobile release 🚀 

Thank you for your contribution @willbrowningme

**Pull request merged**
