### PR TITLE
[Mobile Automation] Adding automationID on mobile elements

### PR DESCRIPTION
**Pull request by ifernandezdiaz**
## Type of change
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other

## Objective
To improve the reliability of our mobile automated tests, we started to add `AutomationIDs` for the most important elements in our `mobile` app.
This branch will be not merged to `master` for now. It will be updated regularly with the latest updates. Once we finish with the locators, we can discuss if we can merge the changes to `master` or not.
NOTE: We should run a regression suite to confirm accessibility is not broken for these updates 

## Code changes
Adding `AutomationIDs` labels for every element we interact in our automated tests.

## Screenshots

Screenshot 2023-04-13 at 14 14 56

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by fedemkr** [comment]
❓ Shall we start adding `AutomationId` on main controls like buttons or text fields on new features? Or is it better to wait until we know UI tests will be created for the feature?

**Comment by ifernandezdiaz** [comment]
> ❓ @ifernandezdiaz Shall we start adding `AutomationId` on main controls like buttons or text fields on new features? Or is it better to wait until we know UI tests will be created for the feature?

Yes, because that would benefit us a lot (we'll sensitively reduce the time we spend on page object creation)

Here are the criteria I'm following on this draft:

1. Every interactable element should have an AutomationID (Buttons, dropdowns, checkboxes, textboxes, etc)
2. Every label that shows dynamic data should have an AutomationID (Item counters on Vault page, Vault Timeout status on Settings Page, Uploaded File Name on Attachments Page, etc)
3. Cells (and cell's content) should have an AutomationID

For feature testing, we (the QAE assigned to the story) should talk with the devs to let them know which elements can be used for our automated tests.

**Comment by fedemkr** [comment]
Great, maybe we could add this in some section on the contributing docs. What do you think?

**Comment by ifernandezdiaz** [comment]
Yes! I agree! Thank you for being so cooperative 🙌

**Pull request closed without merging**
