### PR TITLE
[PS-1896] Add support for Vanadium in GrapheneOS

### PR DESCRIPTION
**Pull request by flawedworld**
## Type of change
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

GrapheneOS changed the package name of Vanadium from org.chromium.chrome to app.vanadium.browser so a new entry is needed for Bitwarden to work with Vanadium. See: https://github.com/GrapheneOS/Vanadium/commit/fd37911a5e927298cefbb77e7460ef76219e7280

## Code changes

I just added app.vanadium.browser as a supported Chromium browser.

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by jceloria — APPROVED** [review]

**Review by Zupe007 — APPROVED** [review]

**Comment by flawedworld** [comment]
If there are any blockers to this pull request please let me know.

**Comment by AlexanderZuehr** [comment]
@vvolkgang 
@mp-bw 
I am sorry for tagging you, but it would we very helpful if you could describe to us what we need to do to get this Pull request accepted. Thank you for your time.

**Review by mp-bw — APPROVED** [review]

**Comment by flawedworld** [comment]
Thank you!

**Comment by BHydden** [comment]
Bitwarden version 2023.1.0
Pixel 6
Android 13
GrapheneOS TQ1A.230105.002.2023011000
Vanadium 109.0.5414.86

Autofill still not working for me either.

**Comment by BHydden** [comment]
> GrapheneOS changed the package name of Vanadium from org.chromium.chrome to app.vanadium.browser so a new entry is needed for Bitwarden to work with Vanadium

If it's relevant, I installed GrapheneOS before this change, so my Vanadium still has the package name

org.chromium.chrome
versionCode 541408633

**Comment by AlexanderZuehr** [comment]
Yeah my package is also:

org.chromium.chrome
versionCode 541408633

and i think it is because of this sentence in the patch notes of graphene os:

> Vanadium: change app id to app.vanadium.browser while using original-package to keep using org.chromium.chrome for existing installs (until factory reset) to preserve compatibility and user data

But in my opinion there shouldnt be a problem for us in the first place, because if the package wasnt renamed for us and the old package has been supported by bitwarden for years. 
So maybe it is a problem inside vanadium?

**Comment by flawedworld** [comment]
The patch works fine, it merely restores the former behaviour to when we formerly were using "org.chromium.chrome".

**Comment by AlexanderZuehr** [comment]
But why isnt it working for me and BHydden anymore?

**Comment by BHydden** [comment]
Yep same for me even though I have the old package name Bitwarden autocomplete broke around the time the new name was added for new installs. Not sure how to diagnose further.

**Comment by jceloria** [comment]
Add me to the list. My wife's Pixel 5 has org.chromium.vanadium and works. My phone has org.chromium.chrome and now no longer works.

**Comment by AlexanderZuehr** [comment]
@flawedworld 
I've seen that you are contributing alot to GrapheneOS. Is it maybe possible for you to have a look at this problem or forward it to the right person?

**Comment by flawedworld** [comment]
Possible that there may be some form of bug in AOSP to do with the package id migration. Needs to be looked into. In the meantime if you can't wait for a fix then try clearing data of Vanadium if that's an option for you.

**Comment by johnceloria** [comment]
I've cleared cache and data a couple of times between reboots and the app is still reporting:
```
version 109.0.5414.86

[org.chromium.chrome](http://org.chromium.chrome/)
versionCode 541408633

targetSdk 33
minSdk 29

Installed: Dec 31, 2008; 19:00
```

**Comment by AlexanderZuehr** [comment]
I've also cleared the data and cache of both apps (vanadium, bitwarden), sadly the behaviour didnt change and it is still not working.

**Comment by Enlinks** [comment]
Testing on a formated device this unfortunately still isn't working. Works just fine on my other browser (Fennec)

version 109.0.5414.86

app.vanadium.browser
versionCode 541408633

targetSdk 33
minSdk 29

Installed: Jan 1, 2009; 12:00 AM

**Comment by m-delc** [comment]
Bitwarden autofill does not work on my GrapheneOS device

`version 110.0.5481.61
app.vanadium.browser
versionCode 548106133
targetSdk 33
minSdk 29
Updated: Dec 31, 2008; 6:00 PM

version 2023.1.0
com.x8bit.bitwarden
versionCode 5786
targetSdk 33
minSdk 21
Installed: Feb 4, 2023; 11:49 AM
Updated: Feb 6, 2023; 8:11 AM`

**Comment by Enlinks** [comment]
Been working with the GrapheneOS team and it looks like to get this to work is a bit tedious but possible.

I was only able to get it working with the new ```app.vanadium.browser``` however.

https://github.com/GrapheneOS/Vanadium/issues/244

> Try following this instruction from GrapheneOS Testing room:
> 
> https://matrix.to/#/!AUltSswJuGkDFXqGti:grapheneos.org/$SGtho6Zk9gv6LGPd981enOVSzTyEyzqVMzRk11rDoDE?via=grapheneos.org&via=matrix.org&via=tchncs.de
> 
> Quote:
> > I have bitwarden autofill working but it was a real pain. In the bitwarden settings for auto-fill services, I needed to enable all 4 options. Vanadium can't handle inliine autofill but draw-over works. The problem occurs when toggling Use accessibility and Bitwarden is grayed out. Tap it to see that it's restricted. You have to give BW permission by going into Settings>Apps>Bitwarden (not within the app but regular settings). Hopefully there will be three dots upper right hand corner. Select and allow restricted. Now, go back to the bitwarden app and select Use Accessibility again. Tihs time it should not be grayed out. Tap it to enable it. Then, finally, go back to the Bitwarden settings to enable draw over. Follow prompts to allow.
>

**Comment by BHydden** [comment]
> I was only able to get it working with the new `app.vanadium.browser`

I have done all 4 steps and can confirm it does not fix the problem for the old  `org.chromium.chrome` app name

Pixel 6 Oriole TQ1A.230205.002.2023021000

Vanadium Version 110.0.5481.64
org.chromium.chrome
versionCode 548106433

Really hoping to find a solution to this problem that doesn't involve formatting my device.

**Comment by raptor170** [comment]
Also same issue here, have the newest bitwarden version installed and doesn't work on vanadium, works well on Firefox etc.

Pixel 6
Grapheneos

Vanadium
Version 110.0.5481.65

org.chromium.chrome
versionCode 548106533

**Comment by ljrk0** [comment]
This is closed as wontfix right now on GrapheneOS side as a better solution is underway at https://github.com/GrapheneOS/Vanadium/issues/276.

The way autofill did work before was to (ab)use accessibility features instead of the actual Auto Fill API to mimick the latter in BitWarden.  Actual Auto Fill never worked in Chrome/Chromium/Vanadium/... because it has its own Play AutoFill capabilities.  Only this crutch, which also required putting Vanadium on this allow list.

Vanadium will implement Android Auto Fill properly (see above) which should solve the issue.

**Comment by BHydden** [comment]
This is fixed now with https://github.com/GrapheneOS/Vanadium/releases/tag/110.0.5481.154.1

**Pull request merged**
