### PR TITLE
Fix accessibility tile bugs

### PR DESCRIPTION
**Pull request by jlf0dev**
- AccessibilityActivity.cs: Tile not working when Bitwarden is open in background
- AccessibilityService.cs: Tile not working when Autofill is enabled and suggestions are showing

### CODE REVIEW

**Review by mportune-bw — APPROVED** [review]

**Comment by fedemkr** [comment]
@jlf0dev  @mp-bw should this be still on hold?

**Comment by jlf0dev** [comment]
These fixes were intended for inconsistencies I encountered a while ago using the Accessibility Tile. I haven't been able to reproduce these in a while, and haven't heard of any reports, so I'm hesitant to check in these changes.

**Comment by fedemkr** [comment]
oh ok, @vvolkgang shall we ask QA if they can reproduce this on other devices? So that we can either merge/close it

**Comment by vvolkgang** [comment]
@fedemkr Let's close for now and re-evaluate if issues come up in the future. Thanks both for following up!

**Pull request closed without merging**
