### PR TITLE
Update support for Ungoogled Chromium browser. Fixes #1118

### LINKED ISSUE #1118: Support for newer builds of Ungoogled Chromium
Bitwarden already supports [Ungoogled Chromium](https://github.com/wchen342/ungoogled-chromium-android)  browser as added here https://github.com/bitwarden/mobile/issues/969. Newer builds however, are not supported because they changed the package name from `org.ungoogled.chomium` to `org.ungoogled.chomium.stable`

Please add the latest package name to supported browsers.

### PR DESCRIPTION
**Pull request by contribucious**
### This:
- updates support for **Ungoogled Chromium** browser.

# Details
- keeps (for a few months)  `org.ungoogled.chromium` with the comment `// [DEPRECATED]`;
- adds `org.ungoogled.chromium.stable`, but also `org.ungoogled.chromium.extensions.stable` (see [their CHANGELOG](https://git.droidware.info/wchen342/ungoogled-chromium-android/src/commit/1812d0258510535da8406ea0e39cdd0c26a21342/CHANGELOG.md) regarding this).
&nbsp;

Fixes #1118

### CODE REVIEW

**Comment by mportune-bw** [comment]
@contribucious Can you take a look at the conflicts here?  (I assume it's because I just merged your Firefox updates)

**Review by mportune-bw — APPROVED** [review]
Thanks @contribucious !

**Comment by contribucious** [comment]
@mportune-bw Yes. Done. Should be OK now. :thumbsup:

**Comment by contribucious** [comment]
@mportune-bw :v:

**Comment by contribucious** [comment]
# :bulb: Appendix
&nbsp;

## :large_blue_diamond: About `org.ungoogled.chromium.stable` entry

```bash
$ aapt dump badging ChromeModernPublic_arm64.apk | grep "package"
package: name='org.ungoogled.chromium.stable' versionCode='418312115' versionName='85.0.4183.121' compileSdkVersion='29' compileSdkVersionCodename='10'

$ strings -f ChromeModernPublic_arm64.apk | grep -w "url_bar"
ChromeModernPublic_arm64.apk: url_bar
```
_v85.0.4183.121-1, [the last one currently available](https://git.droidware.info/wchen342/ungoogled-chromium-android/src/tag/85.0.4183.121-1?lang=en-US) ([here](https://git.droidware.info/wchen342/ungoogled-chromium-android/releases?lang=en-US))._

:fast_forward: **resource-id =** `url_bar`
&nbsp;

## :large_blue_diamond: About `org.ungoogled.chromium.extensions.stable` entry
```bash
$ aapt dump badging Extensions_ChromeModernPublic_arm.apk | grep "package"
package: name='org.ungoogled.chromium.extensions.stable' versionCode='418312110' versionName='85.0.4183.121' compileSdkVersion='29' compileSdkVersionCodename='10'

$ strings -f Extensions_ChromeModernPublic_arm.apk | grep -w "url_bar"
Extensions_ChromeModernPublic_arm.apk: url_bar
```
_v85.0.4183.121-1-Extensions, [the last one currently available](https://git.droidware.info/wchen342/ungoogled-chromium-android/src/tag/85.0.4183.121-1-extensions?lang=en-US) ([here](https://git.droidware.info/wchen342/ungoogled-chromium-android/releases?lang=en-US)) — only an **armeabi-v7a** version currently exists._

:fast_forward: **resource-id =** `url_bar`

**Pull request merged**
