### PR TITLE
Add support for Mull browser

### LINKED ISSUE #1288: Autofill Support for Mull Browser (secure Firefox fork)
Autofill does not currently work on Mull Browser in Android (us.spotco.fennec_dos).

Mull Browser is a fork of Firefox for Android, built for better security and privacy, with proprietary blobs removed.
https://github.com/Divested-Mobile/mull-fenix
https://gitlab.com/divested-mobile/mull

### PR DESCRIPTION
**Pull request by howyay**
This adds support for Mull browser, a privacy oriented and deblobbed web browser based on Mozilla's Firefox for Android. 

Also adds support for legacy version of Mull based on the Fennec architecture.

Resolves #1288

### CODE REVIEW

**Review by cscharf — APPROVED** [review]

**Comment by cscharf** [comment]
Thanks @howyay , will merge this in after our upcoming release.

**Comment by SingingFrog7** [comment]
Hello

You guys made 4 releasea since it was put on hold. Any idea when we can expect it to be merged and released?

Thanks

**Comment by howyay** [comment]
> 
> 
> Hello
> 
> You guys made 4 releases since it was put on hold. Any idea when we can expect it to be merged and released?
> 
> Thanks

Good work :)

**Comment by SingingFrog7** [comment]
I know devs are working hard and this commit could have been forgetten. I didn't switch to mull mainly because of the lack of support from Bitwarden and I am happy it will be the case in next release!

Thanks everybody for your work and time!

**Comment by cscharf** [comment]
Hi @howyay  & @SingingFrog7 , very sorry this got missed. We're making vast improvements with every release to the way we track our community contributions (and our own) through the testing and release process and will soon be making changes to our mobile repo's release and branching model to match other repos so we can test and merge these faster into `master` for upcoming releases going forward (vs. having to wait and "remember" them later).

**Comment by SingingFrog7** [comment]
Hello @theuser18,

    The fix was merged just after @cscharf comment, so Mull is now supported correctly by the Android app. I have been using it since then and it works exactly the same way as other Firefox forks. The same bug with the fields not being filled when the vault was locked apply here, but it's the same as with Firefox, Fennec and other forks.

I guess this issue can be closed

**Pull request merged**
