### PR TITLE
Android + iOS screenshot updates

### PR DESCRIPTION
**Pull request by tgreer-bw**
- Added new Android Screenshots
- New Android Feature image
- New iOS Screenshots for branding
- 5.8" iOS Screenshots added

### CODE REVIEW

**Comment by kspearrin** [comment]
Some of these are not the correct demensions. Just looking at a few I saw this:

image


image

**Comment by tgreer-bw** [comment]
Validated that 6.5" iPhone X and iPad Pro #5 were the only items affected, adjusted those images.

**Comment by tgreer-bw** [comment]
@kspearrin  just a bump for this PR

**Comment by kspearrin** [comment]
Is this an issue? It's showing a notched device on the new screenshots. Apple would likely reject if this type of device is not available on this screen size

image

**Comment by tgreer-bw** [comment]
The new screenshot generator handled all 6.5" screens as iPhone X styling - but I have converted iPhone 6+ screens in this [commit ](https://github.com/bitwarden/mobile/pull/971/commits/3cdbc51b09cb496b04709bd91fde6d0083fd5b74)

**Comment by vachan-maker** [comment]
I was just wondering why these  images still haven't been uploaded to the Play Store and App Store. They look really good and modern.  Now it kind of feels odd to see the old light blue color scheme.

**Review by kspearrin — APPROVED** [review]

**Comment by vachan-maker** [comment]
😃😄
https://user-images.githubusercontent.com/65799568/109382442-7c78fa80-7906-11eb-8bb4-8e79e76e00ff.mp4

**Pull request merged**
