### PR TITLE
[PS-2330][PS-2329][PS-2332][PS-2333] Checking for username terms on Android Autofill

### PR DESCRIPTION
**Pull request by aj-rosado**
## Type of change
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Improving the way we recognize fields as Username and Password at the login autofill to avoid filling username fields with passwords or not detecting username fields as valid username fields

## Code changes

* **FieldCollection.cs:** Added common username terms 
On fields that identify as password we check if they don't have "Username terms" on hints to avoid filling passwords on usernames.
In cases we haven't found any Username Field, we will check if there is any Field with any hint or IdEntry that matches our "Username Terms"

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by mp-bw — APPROVED** [review]

**Comment by larena1** [comment]
I see this is already merged but you might want to include fields having TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS set in username fields and exclude these from password fields to further improve the detection rate. 

https://github.com/bitwarden/mobile/issues/1389#issuecomment-1399327956

**Comment by larena1** [comment]
I can confirm that with your fix Bitwarden will finally properly fill the username when logging in to PayPal but on https://accounts.google.com/ it still fills the password into the username field.

**Comment by federicom09** [comment]
Hello @larena1, thank you for reporting this!

We tried to reproduce the issue on https://accounts.google.com/ while running the latest build from Master but we couldn’t.
Could you please tell us what steps you are following to reproduce the issue?

Thanks!

**Comment by larena1** [comment]
```
diff --git a/FieldCollection.cs b/FieldCollection.cs
index 8b29ab8..3213e15 100644
--- a/FieldCollection.cs
+++ b/FieldCollection.cs
@@ -102,7 +102,7 @@ namespace Bit.Droid.Autofill
 
                     if (!_usernameFields.Any())
                     {
-                        _usernameFields = Fields.Where(f => FieldHasUsernameTerms(f)).ToList();
+                        _usernameFields = Fields.Where(f => FieldIsUsername(f)).ToList();
                     }
                 }
                 return _usernameFields;
@@ -327,7 +327,7 @@ namespace Bit.Droid.Autofill
             }
 
             return inputTypePassword && !ValueContainsAnyTerms(f.IdEntry, _ignoreSearchTerms) &&
-                !ValueContainsAnyTerms(f.Hint, _ignoreSearchTerms) && !FieldHasUsernameTerms(f);
+                !ValueContainsAnyTerms(f.Hint, _ignoreSearchTerms) && !FieldIsUsername(f);
         }
 
         private bool FieldHasPasswordTerms(Field f)
@@ -335,6 +335,11 @@ namespace Bit.Droid.Autofill
             return ValueContainsAnyTerms(f.IdEntry, _passwordTerms) || ValueContainsAnyTerms(f.Hint, _passwordTerms);
         }
 
+        private bool FieldIsUsername(Field f)
+        {
+            return f.InputType.HasFlag(InputTypes.TextVariationWebEmailAddress) || FieldHasUsernameTerms(f);
+        }
+
         private bool FieldHasUsernameTerms(Field f)
         {
             return ValueContainsAnyTerms(f.IdEntry, _usernameTerms) || ValueContainsAnyTerms(f.Hint, _usernameTerms);

```

Field has IdEntry "identifierId" which does not contain any of the terms introduced in this PR. Feel free to use the patch above. It will make Bitwarden finally fill the email into the proper field.

**Comment by dwbit** [comment]
Thanks for the detailed feedback, we are still unable to reproduce this issue on our end but will continue to investigate.

**Comment by larena1** [comment]
@dwbit which part of the code is making bitwarden classify the field as username for you exactly? Is it the code that was introduced in this PR? If so, what is IdEntry of the field set to?

And have you considered my approach or is there anything in particular why you're against considering TextVariationWebEmailAddress as username field?

**Pull request merged**
