### PR TITLE
add microsoft package to support beta/dev/canary

### PR DESCRIPTION
**Pull request by laymanZ**
add package for support Microsoft Edge Beta/Canary/Dev version.

### CODE REVIEW

**Comment by contribucious** [comment]
Hello @laymanZ,

Thank you for your contribution. :wink:
However, as pointed out [here](https://github.com/bitwarden/mobile/blob/d7014adcaa1dfa651d70a3c4cd0fcbf1f5efb55a/src/Android/Autofill/AutofillHelpers.cs#L46-L48), don't forget to add your values [here](https://github.com/bitwarden/mobile/blob/d7014adcaa1dfa651d70a3c4cd0fcbf1f5efb55a/src/Android/Resources/xml/autofillservice.xml) and [there](https://github.com/bitwarden/mobile/blob/d7014adcaa1dfa651d70a3c4cd0fcbf1f5efb55a/src/Android/Accessibility/AccessibilityHelpers.cs#L29) as well.

Example of a recent addition visible [here](https://github.com/bitwarden/mobile/commit/5c6b9fa471f6a772bad54c4dab99675defc086c1) (Soul browser). :thumbsup:
&nbsp;
___
### Regarding "AccessibilityHelpers.cs":
&nbsp;
- you can add "url_bar" for "com.microsoft.emmx.canary" _(link [Play Store](https://play.google.com/store/apps/details?id=com.microsoft.emmx.canary), link [APKMirror](https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=com.microsoft.emmx.canary))_ as second parameter;
```bash
$ strings -f *.apk | grep -w "url_bar"
com.microsoft.emmx.canary_91.0.859.0-85900015_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk: url_bar
```
- you _probably_ can for "com.microsoft.emmx.beta" therefore, although not testable because not existing on: [Play Store](https://play.google.com/store/apps/details?id=com.microsoft.emmx.beta),  [APKMirror](https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=com.microsoft.emmx.beta), [Google](https://www.google.com/search?q="com.microsoft.emmx.beta");
- you _probably_ can for "com.microsoft.emmx.dev" therefore, although not testable because not existing on: [Play Store](https://play.google.com/store/apps/details?id=com.microsoft.emmx.dev),  [APKMirror](https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=com.microsoft.emmx.dev), [Google](https://www.google.com/search?q="com.microsoft.emmx.dev").
&nbsp;

#### :arrow_right_hook: Regarding the latter two: added just in case by consequence?

**Comment by contribucious** [comment]
# Related

### _Announcement in the news_
:new: [Microsoft releases Edge Canary for Android matching desktop OS browser and features](https://www.windowscentral.com/edge-android-canary-desktop-released) (April 16, 2021)

**Comment by laymanZ** [comment]
Hello @contribucious Thanks for remind , a new commit has been submitted . And thanks for  add related news in comment.  👍

**Comment by contribucious** [comment]
@laymanZ Perfect! :thumbsup: :wink:

**Review by mportune-bw — APPROVED** [review]

**Comment by contribucious** [comment]
@mportune-bw It was quick. Thank you for the reactivity! :thumbsup:

@laymanZ And … there you go! :tada: :relaxed:

**Comment by laymanZ** [comment]
@contribucious Thanks very much ! 🎉 👍

**Comment by contribucious** [comment]
## UPDATE 2021-05-01
&nbsp;
Oh! :wink:

:new: [Now Microsoft Edge Dev Is Joining Canary on Android](https://www.makeuseof.com/microsoft-edge-dev-on-android/) (April 30, 2021)
_(**Beta** will most likely follow as well.)_

**Pull request merged**
