### PR TITLE
Adding kiwi Browser "Dev" package name for autofill support

### PR DESCRIPTION
**Pull request by Indranil012**
## Type of change
- Adding Browser compatibility

## Objective
"com.kiwibrowser.browser.dev" package added which is official kiwi browser package publish on github regularly.

### CODE REVIEW

**Comment by contribucious** [comment]
Hello @Indranil012,
&nbsp;

Thank you for your contribution. :thumbsup:
&nbsp;

<details>
<summary><strong>Pre-review … <em>(click to unfold)</em> :heavy_check_mark:</strong></summary>
&nbsp;

kiwibrowser-dev
```powershell
$ aapt dump badging com.kiwibrowser.browser.dev-1603937442-arm64-github.apk | grep package:\ name
package: name='com.kiwibrowser.browser.dev' versionCode='475801415' versionName='98.0.4758.14' platformBuildVersionName=''
```
:heavy_check_mark: _Confirmed_ — see the [current latest release](https://github.com/kiwibrowser/src.next/releases/tag/1603937442) (the tested one) or [all releases](https://github.com/kiwibrowser/src.next/releases).
</details>
&nbsp;
&nbsp;

:arrow_right: Don't forget to remove your ["Test" part](https://github.com/bitwarden/mobile/pull/1694/commits/6c52c0deb5f70159979a3a6d2971da7224f6181f) before the team review, though. :wink:

**Review by vvolkgang — APPROVED** [review]

**Comment by vvolkgang** [comment]
@Indranil012 sorry for the delay, thanks for your contribution! <3 

@contribucious that was great, thanks for the early review and help!

**Comment by vvolkgang** [comment]
@Indranil012 sorry for the delay, thanks for your contribution! :blue_heart:

@contribucious that was great, thanks for the early review and help!

**Comment by contribucious** [comment]
@vvolkgang :v: :wink:

**Pull request merged**
