### PR TITLE
Tweak icons to better blend with Android and iOS

### PR DESCRIPTION
**Pull request by LaurentTreguier**
This PR make the icons deviate from the normal brand ones to attempt at having a more "seamless" look depending on the platform.
The Android icon has a shadow added like many Google apps have, while the iOS icon has a gradient like many Apple apps have.
Both icons have a slightly smaller shield. In Android, this makes the round icon feel just a tiny bit less cramped. On iOS, this is coupled with the shield being moved down a little to make it look more balanced.

I don't know if it would be accepted to not use the exact brand icon, but the icon is one of the first things we see on app stores, and small tweaks can go a long way.

---

Android icon foreground (background is the same `#175DDC`):
```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 600 600">
    <defs>
        <linearGradient gradientTransform="rotate(45)" id="shadow">
            <stop offset="0%" stop-color="#0000003F"/>
            <stop offset="100%" stop-color="#00000000"/>
        </linearGradient>
    </defs>
    <g transform="translate(105 85)">
        <polygon fill="url(#shadow)" points="377,13 795,431 560,865 65,370 195,445 370,270"/>
        <path fill="white" d="M376.4,12.2c-3.7-3.7-8.1-5.6-13.1-5.6H26.7c-5.1,0-9.4,1.9-13.1,5.6C9.9,15.9,8,20.2,8,25.3
	v224.4c0,16.7,3.3,33.4,9.8,49.8c6.5,16.5,14.6,31.1,24.3,43.8c9.6,12.8,21.1,25.2,34.5,37.2c13.3,12.1,25.7,22.1,37,30.1
	c11.3,8,23.1,15.5,35.4,22.6c12.3,7.1,21,11.9,26.2,14.5c5.2,2.5,9.3,4.5,12.4,5.8c2.3,1.2,4.9,1.8,7.6,1.8c2.7,0,5.3-0.6,7.6-1.8
	c3.1-1.4,7.3-3.3,12.4-5.8c5.2-2.5,13.9-7.4,26.2-14.5c12.3-7.1,24.1-14.7,35.4-22.6c11.3-8,23.6-18,37-30.1
	c13.3-12.1,24.8-24.5,34.5-37.2c9.6-12.8,17.7-27.4,24.2-43.8c6.5-16.5,9.8-33.1,9.8-49.8V25.3C382,20.2,380.1,15.9,376.4,12.2z
	 M333,251.8C333,333,195,403,195,403V54.6h138C333,54.6,333,170.6,333,251.8z"/>
    </g>
</svg>
```

iOS icon:
```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 600 600">
    <defs>
        <linearGradient id="gradient" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#578DFC"/>
            <stop offset="100%" stop-color="#074DCC"/>
        </linearGradient>
    </defs>
    <rect width="600" height="600" fill="url(#gradient)"/>
    <path transform="translate(105 85)" fill="white" d="M376.4,12.2c-3.7-3.7-8.1-5.6-13.1-5.6H26.7c-5.1,0-9.4,1.9-13.1,5.6C9.9,15.9,8,20.2,8,25.3
	v224.4c0,16.7,3.3,33.4,9.8,49.8c6.5,16.5,14.6,31.1,24.3,43.8c9.6,12.8,21.1,25.2,34.5,37.2c13.3,12.1,25.7,22.1,37,30.1
	c11.3,8,23.1,15.5,35.4,22.6c12.3,7.1,21,11.9,26.2,14.5c5.2,2.5,9.3,4.5,12.4,5.8c2.3,1.2,4.9,1.8,7.6,1.8c2.7,0,5.3-0.6,7.6-1.8
	c3.1-1.4,7.3-3.3,12.4-5.8c5.2-2.5,13.9-7.4,26.2-14.5c12.3-7.1,24.1-14.7,35.4-22.6c11.3-8,23.6-18,37-30.1
	c13.3-12.1,24.8-24.5,34.5-37.2c9.6-12.8,17.7-27.4,24.2-43.8c6.5-16.5,9.8-33.1,9.8-49.8V25.3C382,20.2,380.1,15.9,376.4,12.2z
	 M333,251.8C333,333,195,403,195,403V54.6h138C333,54.6,333,170.6,333,251.8z"/>
</svg>
```

### CODE REVIEW

**Comment by kspearrin** [comment]
Could you include some images of these changes?

**Comment by LaurentTreguier** [comment]
Sure, here is the result on both platforms:
|Android|iOS|
|---|---|
|Android|iOS|

Github's rich diff feature can also be useful to compare, with this PR I checked it and learned that it can even use multiple ways of comparing the images. (though there's hardly any replacement for seeing them in context)

**Comment by mportune-bw** [comment]
Can you provide screenshots on Android using all possible adaptive shapes?  We recently spent some time making the shield appear more vertically balanced across the shapes and want to make sure it still holds.

**Comment by LaurentTreguier** [comment]
Good point !
Any shape is a possible shape technically though; I don't know how to properly test this. What did you use to check the vertical centering ?
For now I tried [AdaptiveIconPlayground](https://github.com/nickbutcher/AdaptiveIconPlayground):

|Screenshot_1591562778|Screenshot_1591562782|
|---|---|
|Screenshot_1591562785|Screenshot_1591562788|

**Comment by mportune-bw** [comment]
Thanks.  For testing we just changed the shape from developer settings on the Pixel.  Your examples from AdaptiveIconPlayground work too though.

I like these, they add some needed (and native looking) depth to the launcher icons for both platforms.  What are your thoughts @kspearrin @cscharf @vincentsalucci ?

**Pull request merged**
