### PR TITLE
Supress lock and logout when showing fileswitcher on Android

### PR DESCRIPTION
**Pull request by jlf0dev**
## Type of change
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

If vault timeout was set to "Immediate", the file picker on Android was locking and logging out Bitwarden. This meant you could never choose a file.

This fix adds a `DelayLockAndLogoutMs` long to the VaultTimeoutService and sets it to 60 seconds while choosing an attachment on Android.

I also removed the extraneous logic for lock/logout from App.xaml.cs. I consolidated this logic in `CheckVaultTimeoutAsync()` inside the VaultTimeoutService.

## Code changes

* **IVaultTimeoutService.cs:** Add DelayLockAndLogoutMs long to TimeoutService
* **VaultTimeoutService.cs:** Add logic to check for DelayLockAndLogoutMs when checking VaultTimeout settings
* **AttachmentsPageViewModel.cs:** If Android, set DelayLockAndLogoutMs to 60s before showing filepicker
* **App.xaml.cs:** Reset DelayLockAndLogoutMs and move lock/logout logic to VaultTimeoutService

## Testing requirements

- User can pick an attachment while the VaultTimeout option is set to "Immediate"
- Functionality of VaultTimeout still works

## Before you submit
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by djsmith85** [comment]
Possibly also related to #385

**Review by eliykat — COMMENTED** [review]
I don't know enough about mobile to do the code review, but my question about this approach is whether it could accidentally leave `SuppressLockLogout` set to `true`. e.g.
* what if the user locks the screen from the file picker?
* what if the user changes app from the file picker?
* any other code flows / user interactions that could evade setting it back to `false`?

**Comment by jlf0dev** [comment]
These are good questions @eliykat and I'm not completely happy with how I fixed this. Let me take a second look and see if we can accomplish this any other way.

**Comment by mportune-bw** [comment]
Good points brought up by @eliykat .  I don't think there's a clean way to handle points 1 & 2 without over-engineering something truly awful, but handling points 3 & 4 should probably cover it.  To expand on point 4, how about making `SuppressLockLogout` a timestamp (nullable `long`) instead of a bool, then compare to a hardcoded threshold upon returning to the app if it's not null?  You can use `_deviceActionService.GetActiveTime()` to get a monotonic timestamp in milliseconds, and give the user, let's say 45-60 seconds to select an attachment.

**Comment by jlf0dev** [comment]
Changed my approach here to follow @mportune-bw's suggestion. I like this strategy better, should be a little more bulletproof.

**Review by mportune-bw — APPROVED** [review]

**Pull request merged**
