### PR TITLE
[PM-1627] Add android autofill support for org.chromium.chrome.stable

### PR DESCRIPTION
**Pull request by nielscil**
## Type of change
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other

## Objective

Autofill wasn't working for macchrome's [Chromium](https://github.com/macchrome/droidchrome). With this PR I've added the package name to the autofill and accessibilityhelper to fix this issue.

## Code changes

* **src/Android/Accessibility/AccessibilityHelpers.cs:** Added Browser object with package name
* **src/Android/Autofill/AutofillHelpers.cs:** Added package name
* **src/Android/Resources/xml/autofillservice.xml:** Added package

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by nielscil** [comment]
Is there any progress in reviewing this PR?

**Comment by dbosompem** [comment]
Hi @neilsb, the Github link you shared for Chromium seems empty so this becomes a bit unclear. Can you provide an updated link for the team to review? Thanks!

**Comment by neilsb** [comment]
> Hi @neilsb, the Github link you shared for Chromium seems empty so this becomes a bit unclear. Can you provide an updated link for the team to review? Thanks!

Think @nielscil was the intended tag-ee.

**Comment by dbosompem** [comment]
Closing this as we've not heard back from you, @nielscil. We will review this if additional details requested are provided. Thanks!

**Pull request closed without merging**
