### PR TITLE
reposition buttons in Log In and Unlock pages

### PR DESCRIPTION
**Pull request by eliykat**
## Description
I have repositioned the buttons in the Log In and Unlock (i.e. Verify Master Password) pages as discussed in [this Community Forums thread](https://community.bitwarden.com/t/reposition-buttons-in-verify-master-password-and-log-in-screens-on-mobile/14326). The intention of this is to improve the positioning of primary buttons and the UX flow as the user moves through these pages.

*Log In page:* move Log In button to primary location below password entry, move Get Your Master Password Hint to the More Options menu. [Screenshot](https://user-images.githubusercontent.com/31796059/93534423-6561d400-f988-11ea-803c-237a11d79e4c.PNG)

*Unlock page (Verify Master Password):* swap position of Unlock and Log Out buttons. [Screenshot](https://user-images.githubusercontent.com/31796059/93534441-6e52a580-f988-11ea-82a2-bddc5bf2f909.PNG)

## Changes not implemented
In the Community Forums thread, we discussed putting an icon on the Unlock button and changing the theming of primary buttons (i.e. to use the Bitwarden colour scheme rather than the current grey). 

However, this was more complicated than anticipated to implement properly and to get it looking good across all devices. I also think that any change to button theming should be implemented consistently across the app, as these buttons appear in other places that were not the subject of this contribution. I still think this needs to be changed, but it should be a separate contribution so that it can be properly considered and implemented consistently across the app.

## Testing
I have tested this in iOS and Android and it all works well subject to the following.

It appears that the Get Your Master Password Hint button is hidden when launching the login flow a certain way in iOS. See the changes to CredentialProviderViewController.cs and LoadingViewController.cs. I have updated these references as required but I was unable to test them because of issues with my iOS development environment. (Briefly, I don't have a provisioning profile or Apple Developer account, so I had to disable custom entitlements to get this to build, which broke certain features of the app such as autofill.) I recommend someone does a quick test of this login flow before accepting the PR.

### CODE REVIEW

**Review by cscharf — COMMENTED** [review]
Screen shots look good, changes also look good from the surface but I'll let @mportune-bw and/or @kspearrin take a second look as they're more familiar overall.

**Comment by kspearrin** [comment]
I would suggest moving the log out option under the `...` option on the unlock page as you did on the login page.

Also, does it make sense to make both ios and android consistent so we dont need this hide hint option?

**Comment by eliykat** [comment]
On further investigation, the Get Hint button is currently hidden on the following screens in iOS:
- when enabling autofill from Settings for the first time -> this pops up the Bitwarden login screen with no Get Hint button
- when autofilling a password and the vault is locked -> this also pops up the Bitwarden login screen with no Get Hint button

I'm not sure why the Get Hint button is hidden in these circumstances - at a guess, maybe because it interrupts the login flow? There could be some technical reason I'm not sure of. You're right though, it is inconsistent with the behaviour on Android which always has the Get Hint button displayed, even when accessing via the autofill feature.

I'll submit another commit to move the log out button as you suggest and remove this 'hide hint' functionality. However, I've been unable to successfully deploy Bitwarden to an iOS device for testing, so unfortunately I won't be able to test it on iOS. (Even with an Apple Developer account I am still getting provisioning errors and I've spent enough time on it)

**Comment by cscharf** [comment]
> However, I've been unable to successfully deploy Bitwarden to an iOS device for testing, so unfortunately I won't be able to test the autofill flow on iOS. (Even with an Apple Developer account I am still getting provisioning errors that I've hit all dead ends on)

@eliykat , once you're confident this is ready I can pull the branch and test via iOS (and would before approving/merging the PR), no worries. I understand Xcode and Apple dev can be, um..., "difficult" to get working 😉

**Review by cscharf — APPROVED** [review]

**Comment by cscharf** [comment]
Will merge this after our planned patch release today/this week to ensure minimum impact. Thanks again for the contribution @eliykat !

**Comment by vachan-maker** [comment]
@cscharf When will this be merged?

**Comment by cscharf** [comment]
> @cscharf When will this be merged?

Whoops, sorry; @mportune-bw , if you have a moment can you please take a look and prepare a merge? I see some conflicts with the recent work I believe you've been working on.

**Review by mportune-bw — APPROVED** [review]

**Comment by raniesantos** [comment]
THANK YOU SO MUCH FOR CONTRIBUTING THIS AND TO THE PERSON THAT MERGED IT.

This has been bugging me soooooooo long.

I'm just a user, but I felt so strongly about this that I had to comment on it.

**Pull request merged**
