### PR TITLE
Honor user CA store when targeting Android Nougat SDK and later

### PR DESCRIPTION
**Pull request by dNetGuru**
See: https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html

Fixes: #346

### CODE REVIEW

**Comment by kspearrin** [comment]
According to the examples in that blog, it seems we probably want to exclude bitwarden.com endpoints for this, since those should never require custom CA trust.

**Comment by dNetGuru** [comment]
Yes, I didn't add that since I don't have a complete list of all the domains this app contacts.

If everything is hosted under `*.bitwarden.com` then I'll just add an exception `bitwarden.com` and all subdomains and push it in a bit.

**Comment by kspearrin** [comment]
Just add api.bitwarden.com and identity.bitwarden.com. I can add any others.

**Comment by dNetGuru** [comment]
It seems like I can specify `includeSubdomains="true"` to include all sub-domains which would be a better approach. If you're using self-signed CAs for any other subdomain, you could explicitly exclude it by adding another `domain-config` entry.

I was reading further into the docs (here: https://developer.android.com/training/articles/security-config) and I found out that you can opt out of all clear-text traffic which is always a good idea, I also added to the commit.

Let me know if you want me to do the following as well:
There seems to be an option to enable certificate pinning (which could protect the users even in a case of a CA compromise) in the `network_security_config` area but I noticed that you're using Cloudflare SSL which you wouldn't be managing and I'm not sure how often they rotate/regenerate them.
The next best thing would be to specifically specify `COMODO ECC Certification Authority`'s certificate as the only trusted CA for `*.bitwarden.com` since they issue all the Cloudflare certificates and this way the users are protected from a possible compromise of all the other CAs.

**Comment by kspearrin** [comment]
No need for pinning. Thanks.

**Pull request merged**
